export const walletImages: Record<string, string> = {
  "WalletConnect": "https://images.seeklogo.com/logo-png/43/2/walletconnect-logo-png_seeklogo-430923.png",
  "Ledger Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGEO2EwcAKY5OS5RndSkuXkLy0cSmiWbXF3w&s",
  "MetaMask": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/MetaMask_Fox.svg/1200px-MetaMask_Fox.svg.png",
  "Exodus": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7ac9O_DORRUoTuI9KIR-wAHGYJOEOoDLvkA&s",
  "Uniswap Wallet": "https://cryptologos.cc/logos/uniswap-uni-logo.png",
  "Polkadot Wallet": "https://s3.amazonaws.com/appforest_uf/f1670595972292x285725902843603870/polkadot.png",
  "HashPack Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLtobBLVml7yGPBbfO40Orw7HDP82X1a4z9Q&s",
  "Binance Smart Chain": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSG89viNFBqmyhkyCO4W2UHVF-NV5Qn6AtTzg&s",
  "SafePal Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1CDl_6EEhHjnYVuchge5oqOY1BJ7pJy9CBg&s",
  "Bifrost wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0INqtV6c7kG6-YE8C1SA1EnGEukDxyGpbdg&s",
  "Ledger Live": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGEO2EwcAKY5OS5RndSkuXkLy0cSmiWbXF3w&s",
  "Zerion Wallet": "https://play-lh.googleusercontent.com/lxl3CQLYmbY7kHtMn3ehz06ebEIIxYOETf8hlWPNW6L3ZPxuhSrnIq-4k5T89gd4gA=w240-h480-rw",
  "OKX Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnI5O0sf4FKYntQKmTjB-lqzZzk62i56tEtw&s",
  "XUMM Wallet": "https://pbs.twimg.com/profile_images/1280832346611167236/1sQA2Dn9_400x400.jpg",
  "Coinbase Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReuFM2QKaMfn5Z1n9jUMg3wySi_Cu1Ive_oQ&s",
  "BitGet Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHDRiyge4nb31LvRpRnGXs61sboMpUU42A0A&s",
  "Robinhood Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRi-utj1AxLkrVVq6QdFvQ3yJpbzZB7CJdQ9w&s",
  "ByBit Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjLWTFWl72vwBZexad4NNb43adzoBgwJzdTQ&s",
  "Phantom Wallet": "https://coinlaunch.space/media/images/4/8/5/0/4850.sp3ow1.192x192.png",
  "Trust Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsBrpjUaDrS_CEdrg7km2_08t6ZXPDtg9Tpw&s",
  "Rainbow": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv0n_AIQ_-oDHrqJ5byuJnyU-w4tC-ef2_6g&s",
  "Argent": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsHCOZuf4R7wqYUfT13h2O6kX8caxQzFpVQQ&s",
  "Rabby Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgLPW7LYjMqjb1cKrMneM1ZGnDse5T_3ionw&s",
  "Brave Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgdDD7qlpvjPM_xWzYtijQFuob8pSo5dHaYw&s",
  "Crypto.com | DeFi Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8UiMc9LaKjvdZ9BlHD32dlWEAAIq3hMkxTw&s",
  "imToken": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrTcHlP2Tf6rNVXxDywaxrGP7gd33L9HZ1Og&s",
  "TokenPocket": "https://play-lh.googleusercontent.com/hcnLVaagPA_c8TGRDtV4c3R7mkhw3pAlop1WI4zJjjokJ5DErElAqwqkYriYmRRCaaY",
  "BitPay": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwjHfvlPbNzTAJ6Guz6VXnpN6rG0UdJfgVnA&s",
  "1inch Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdJiTQw1533oqnEgpeejsEIHM6WVz169hlEA&s",
  "Huobi Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaleIiDrpBlhDC_0JmIthi6aul0_ZAZyaXnw&s",
  "MEW Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaoWPuhrzC1LHvEtqxUQvMotXF7gQVdfvYCw&s",
  "Blockchain Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBOLM2CK9o8CE4cxr6gU0dFM3HyxCer3ryvA&s",
  "SafeMoon Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSW9q389DOBbwed1jvG7rtdNSDFihBWBmUB2g&s",
  "Frontier Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnl0Kfg98JmFU2eas2v_isa0zDQ2bUK9f7SQ&s",
  "Tangem Wallet": "https://images.crunchbase.com/image/upload/c_pad,f_auto,q_auto:eco,dpr_1/a5r5vnxlpb0aj4nvmcpd?ik-sanitizeSvg=true",
  "MathWallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRN04hBJLqwxe0dndDvoSMn4JJeyklXMEQ-ag&s",
  "Enjin Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJp7OdVKqTUh5yn3N7nIF2I8quC6Yf956m6A&s",
  "Fetch.ai Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQf405A-7TS7EvSIP1XOenad2Mc-gwK03t8g&s",
  "GateWeb3 Wallet": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4SNWaMtw0fcFHSrIP3cXOvYLy7oCPzZd5VA&s",
};

export const allWallets = [
  "MetaMask", "Exodus", "Ledger Wallet", "Uniswap Wallet", "Polkadot Wallet",
  "HashPack Wallet", "Binance Smart Chain", "SafePal Wallet",
  "Fetch.ai Wallet", "Bifrost wallet", "Ledger Live", "Zerion Wallet",
  "OKX Wallet", "XUMM Wallet", "Coinbase Wallet",
  "GateWeb3 Wallet", "BitGet Wallet", "Robinhood Wallet", "ByBit Wallet",
  "Frontier Wallet", "SafeMoon Wallet",
  "Phantom Wallet", "Enjin Wallet", "Blockchain Wallet", "MEW Wallet",
  "Rabby Wallet",
  "Rainbow", "Trust Wallet", "Argent", "Tangem Wallet",
  "Brave Wallet", "Crypto.com | DeFi Wallet",
  "imToken", "TokenPocket", "MathWallet",
  "BitPay", "1inch Wallet", "Huobi Wallet",
];

export const getWalletImage = (wallet: string): string =>
  walletImages[wallet] || "https://via.placeholder.com/64?text=W";
